# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=50)),
                ('mood', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('energy', models.IntegerField(default=5)),
                ('tempo', models.CharField(choices=[('SS', 'ad lib-60'), ('SM', '61-81'), ('SF', '82-89'), ('MS', '90-97'), ('MM', '98-106'), ('MF', '107-118'), ('FS', '119-124'), ('FM', '125-130'), ('FF', '131-inf.')], default='SS', max_length=2)),
                ('artist_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist1', to='playlist.Artist')),
                ('artist_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist2', to='playlist.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Soundcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='sound_code',
            field=models.ManyToManyField(to='playlist.Soundcode'),
        ),
    ]
