# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
