# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_song_song_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('id',), 'verbose_name': 'Artist', 'verbose_name_plural': 'Artists'},
        ),
        migrations.AlterField(
            model_name='song',
            name='artist_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist2', to='playlist.Artist'),
        ),
    ]
