# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20160901_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soundcode',
            options={'ordering': ('title',), 'verbose_name': 'Soundcode', 'verbose_name_plural': 'Soundcodes'},
        ),
    ]
