# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0006_auto_20160905_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Artist', 'verbose_name_plural': 'Artists'},
        ),
    ]
