# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0007_auto_20160907_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soundcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
