# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import playlist.models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0008_auto_20160909_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='cover',
            new_name='image',
        ),
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=playlist.models.upload_to),
        ),
        migrations.AddField(
            model_name='soundcode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=playlist.models.upload_to),
        ),
    ]
