# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import playlist.models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0009_auto_20160909_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=playlist.models.upload_to),
        ),
    ]
